### ISSUE TITLE
Muted icon status

### ISSUE THREAD

**Issue by sl1pkn07** [kondinskis/hyperx-cloud-flight#1]
Hi

is possible change the icon if the headset is muted?

greetings

**Comment by kondinskis** [comment]
Can you provide more info? 
What distro and icon pack are you using? Because there is already icon for muted state.
![image](https://user-images.githubusercontent.com/7606608/141656878-96cf9cbe-c4a4-4df5-afbb-9eb861a99b64.png)

**Comment by kondinskis** [comment]
I released new version, can you check if it shows the icon now?
https://github.com/kondinskis/hyperx-cloud-flight/releases/tag/0.1.3

**Comment by sl1pkn07** [comment]
yes working! (plasma KDE)

greetings
