### ISSUE TITLE
HyperX Cloud Stinger

### ISSUE THREAD

**Issue by alexwbaule** [kondinskis/hyperx-cloud-flight#10]
Hello !

Do you have the Stinger hid commands ? (to get battery level, etc).

Tks.

**Comment by kondinskis** [comment]
I don't have documentation, but you can try by capturing the bytes on windows by using the official hyperx app.

**Comment by byquip** [comment]
Hi @alexwbaule, did you succeed?

**Comment by alexwbaule** [comment]
No yet.
