### ISSUE TITLE
HyperX Cloud II Wireless

### ISSUE THREAD

**Issue by michalis97500** [kondinskis/hyperx-cloud-flight#14]
Hey, I have a pair of Cloud II Wireless and would love to use this software. Is there a way to figure out what bytes I need to send to my device to get the same reply?

**Comment by kondinskis** [comment]
Check the other issue related to this #13

**Comment by michalis97500** [comment]
That issue mentions the method but only for some actions and not
specifically the battery. I am not experienced enough to reverse engineer
the app, and with that tool running, opening NGenuity does not seem to be
sending anything (at least nothing is captured).
