### ISSUE TITLE
Not found any compatible device

### ISSUE THREAD

**Issue by Ryzeon** [kondinskis/hyperx-cloud-flight#4]
HI, im trying to install it, but throws `thread 'main' panicked at 'Not found any compatible device', src/cloud_flight.rs:75:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
` error :(

**Comment by kondinskis** [comment]
Can you provide output from the following command lsusb | grep "Kingston" ?

**Comment by Ryzeon** [comment]
Sure
![image](https://user-images.githubusercontent.com/60982533/153285435-5ba2d88a-1ba7-46b4-bbf7-f074588f3262.png)

**Comment by kondinskis** [comment]
Have you created the udev rule file ? As shown in the readme?
https://github.com/kondinskis/hyperx-cloud-flight#prerequisites

**Comment by Ryzeon** [comment]
Yep,
![image](https://user-images.githubusercontent.com/60982533/153291983-9b38aab1-e716-42f5-8e2f-b316ebaf64d6.png)

**Comment by kondinskis** [comment]
Hmm, can you check if hidapi is installed on your machine?

- libhidapi-hidraw0 for debian based distros
- hidapi for arch/manjaro

**Comment by Ryzeon** [comment]
Yep libhidapi-hidraw0 is installed

**Comment by kondinskis** [comment]
Did u replug the dongle or maybe tried restarting the pc?

**Comment by Ryzeon** [comment]
When i created /etc/udev/rules.d/99-hyperx-cloud-flight.rules, i replug but doesn't work, i tried to restart  but i get same result

**Comment by kondinskis** [comment]
Did you tried to run it with sudo ?

**Comment by Ryzeon** [comment]
Let me try

**Comment by Ryzeon** [comment]
Works, but there's any icon 😭 
![image](https://user-images.githubusercontent.com/60982533/153295722-6092053b-5ea5-494e-a51b-834c99a2e706.png)
![image](https://user-images.githubusercontent.com/60982533/153295735-d6a741c6-621d-4145-b38d-4066cebc605d.png)

**Comment by kondinskis** [comment]
It's udev related issue, can you provide output from the following command?
`ls -la /etc/udev/rules.d/99-hyperx-cloud-flight.rules`

**Comment by Ryzeon** [comment]
Sure,
![image](https://user-images.githubusercontent.com/60982533/153296116-7a40531b-a7d1-4fbf-a2f1-5bc78b8f4b02.png)

**Comment by kondinskis** [comment]
Can you try with the following rules?
`KERNEL=="hidraw*", ATTRS{idVendor}=="0951", ATTRS{idProduct}=="16c4", MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="0951", ATTRS{idProduct}=="1723", MODE="0666"`
Replug the dongle once u change them.

**Comment by Ryzeon** [comment]
I get the same result, icon doesn't show 😢

**Comment by kondinskis** [comment]
Once you change them, start it without sudo.

**Comment by Ryzeon** [comment]
kk, let me try

**Comment by Ryzeon** [comment]
Now works, tyy

**Comment by kondinskis** [comment]
You're welcome.

**Comment by santiagosuare** [comment]
Same problem, but follow this steps now works. thx!
