### ISSUE TITLE
Icons for dark theme

### ISSUE THREAD

**Issue by poldolot** [kondinskis/hyperx-cloud-flight#7]
Hi, is it possible to add dark theme support? Default icons are almost invisible ;>
Example for muted mic under Ubuntu 20.04:
![image](https://user-images.githubusercontent.com/5675282/161017879-cf8d7bb9-715c-4ffc-adf6-ac294959f675.png)

**Comment by kondinskis** [comment]
What icon pack are you using ?

**Comment by poldolot** [comment]
McMojave, but, if it is dependent on icon pack so there is no issue, I'll change it, thanks for response and great app!
