### ISSUE TITLE
HyperX Cloud 2 Wireless Revision

### ISSUE THREAD

**Issue by RadiantOblivion** [kondinskis/hyperx-cloud-flight#8]
Hello,

I'm looking to possibly revise this for a Cloud 2 Wireless variant. I was able to locate the VID and PID no problem, but are the buffers in cloud_flight.rs assumed or RE'd? Hopefully it's as easy as a drop-in if the buffers work out (praying).

**Comment by kondinskis** [comment]
Firstly I would not recommend trying this on different headset, if you send wrong buffers it might brick your headset.
The buffers in this app are reverse engineered from the windows client.

**Comment by RadiantOblivion** [comment]
I was afraid of that, alright thank you.
