### ISSUE TITLE
App stuck loading

### ISSUE THREAD

**Issue by santiagosuare** [kondinskis/hyperx-cloud-flight#9]
The app stuck when i charge de hyperx cloud flight. Y reset de app, reset pc, and still say like headset sill charging.
Some way to solve? 

![image](https://user-images.githubusercontent.com/91102705/166127073-60ccebbd-fbba-48fe-8f46-613a47683135.png)

![image](https://user-images.githubusercontent.com/91102705/166127273-c460380b-d01a-401f-a47e-c68b2b4e26c7.png)

**Comment by kondinskis** [comment]
It does not report battery percentage when charging, once fully charged it will show `Battery 100%`.
